### ISSUE TITLE
osv-scanner action fails

### ISSUE THREAD

**Issue by cherdt** [cherdt/vader-webform#23]
The error message is:

```
Invalid workflow file: .github/workflows/osv-scanner.yml#L31
The workflow is not valid. .github/workflows/osv-scanner.yml (Line: 31, Col: 3): Error calling workflow 'google/osv-scanner-action/.github/workflows/osv-scanner-reusable.yml@764c91816374ff2d8fc2095dab36eecd42d61638'. The workflow is requesting 'actions: read', but is only allowed 'actions: none'.
```

I'm honestly not positive what it's looking for here. I did note the following differences between my file and the example in the docs:

```
permissions:
  # Require writing security events to upload SARIF file to security tab
  security-events: write
  # Read commit contents
  contents: read
```

versus

```
permissions:
  # Required to upload SARIF file to CodeQL. See: https://github.com/github/codeql-action/issues/2117
  actions: read
  # Require writing security events to upload SARIF file to security tab
  security-events: write
  # Only need to read contents
  contents: read
```

(see https://google.github.io/osv-scanner/github-action/)
